// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: cbws/logging/v1alpha1/log_severity.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The severity of the event described in a log entry, expressed as one of the
// standard severity levels listed below.  For your reference, the levels are
// assigned the listed numeric values. The effect of using numeric values other
// than those listed is undefined.
//
// You can filter for log entries by severity.  For example, the following
// filter expression will match log entries with severities `INFO`, `NOTICE`,
// and `WARNING`:
//
//     severity > DEBUG AND severity <= WARNING
//
// If you are writing log entries, you should map other severity encodings to
// one of these standard levels. For example, you might map all of Java's FINE,
// FINER, and FINEST levels to `LogSeverity.DEBUG`. You can preserve the
// original severity level in the log entry payload if you wish.
type LogSeverity int32

const (
	// (0) The log entry has no assigned severity level.
	LogSeverity_LOG_SEVERITY_UNSPECIFIED LogSeverity = 0
	// (100) Debug or trace information.
	LogSeverity_LOG_SEVERITY_DEBUG LogSeverity = 100
	// (200) Routine information, such as ongoing status or performance.
	LogSeverity_LOG_SEVERITY_INFO LogSeverity = 200
	// (300) Normal but significant events, such as start up, shut down, or
	// a configuration change.
	LogSeverity_LOG_SEVERITY_NOTICE LogSeverity = 300
	// (400) Warning events might cause problems.
	LogSeverity_LOG_SEVERITY_WARNING LogSeverity = 400
	// (500) Error events are likely to cause problems.
	LogSeverity_LOG_SEVERITY_ERROR LogSeverity = 500
	// (600) Critical events cause more severe problems or outages.
	LogSeverity_LOG_SEVERITY_CRITICAL LogSeverity = 600
	// (700) A person must take an action immediately.
	LogSeverity_LOG_SEVERITY_ALERT LogSeverity = 700
	// (800) One or more systems are unusable.
	LogSeverity_LOG_SEVERITY_EMERGENCY LogSeverity = 800
)

// Enum value maps for LogSeverity.
var (
	LogSeverity_name = map[int32]string{
		0:   "LOG_SEVERITY_UNSPECIFIED",
		100: "LOG_SEVERITY_DEBUG",
		200: "LOG_SEVERITY_INFO",
		300: "LOG_SEVERITY_NOTICE",
		400: "LOG_SEVERITY_WARNING",
		500: "LOG_SEVERITY_ERROR",
		600: "LOG_SEVERITY_CRITICAL",
		700: "LOG_SEVERITY_ALERT",
		800: "LOG_SEVERITY_EMERGENCY",
	}
	LogSeverity_value = map[string]int32{
		"LOG_SEVERITY_UNSPECIFIED": 0,
		"LOG_SEVERITY_DEBUG":       100,
		"LOG_SEVERITY_INFO":        200,
		"LOG_SEVERITY_NOTICE":      300,
		"LOG_SEVERITY_WARNING":     400,
		"LOG_SEVERITY_ERROR":       500,
		"LOG_SEVERITY_CRITICAL":    600,
		"LOG_SEVERITY_ALERT":       700,
		"LOG_SEVERITY_EMERGENCY":   800,
	}
)

func (x LogSeverity) Enum() *LogSeverity {
	p := new(LogSeverity)
	*p = x
	return p
}

func (x LogSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_cbws_logging_v1alpha1_log_severity_proto_enumTypes[0].Descriptor()
}

func (LogSeverity) Type() protoreflect.EnumType {
	return &file_cbws_logging_v1alpha1_log_severity_proto_enumTypes[0]
}

func (x LogSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSeverity.Descriptor instead.
func (LogSeverity) EnumDescriptor() ([]byte, []int) {
	return file_cbws_logging_v1alpha1_log_severity_proto_rawDescGZIP(), []int{0}
}

var File_cbws_logging_v1alpha1_log_severity_proto protoreflect.FileDescriptor

var file_cbws_logging_v1alpha1_log_severity_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x62, 0x77, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x62, 0x77, 0x73,
	0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2a, 0xfb, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74,
	0x79, 0x12, 0x1c, 0x0a, 0x18, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54,
	0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f,
	0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x64, 0x12, 0x16, 0x0a, 0x11, 0x4c, 0x4f, 0x47, 0x5f, 0x53,
	0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0xc8, 0x01, 0x12,
	0x18, 0x0a, 0x13, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f,
	0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10, 0xac, 0x02, 0x12, 0x19, 0x0a, 0x14, 0x4c, 0x4f, 0x47,
	0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e,
	0x47, 0x10, 0x90, 0x03, 0x12, 0x17, 0x0a, 0x12, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x56, 0x45,
	0x52, 0x49, 0x54, 0x59, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xf4, 0x03, 0x12, 0x1a, 0x0a,
	0x15, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x43, 0x52,
	0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0xd8, 0x04, 0x12, 0x17, 0x0a, 0x12, 0x4c, 0x4f, 0x47,
	0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x10,
	0xbc, 0x05, 0x12, 0x1b, 0x0a, 0x16, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49,
	0x54, 0x59, 0x5f, 0x45, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x4e, 0x43, 0x59, 0x10, 0xa0, 0x06, 0x42,
	0x77, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x62,
	0x77, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x62, 0x77, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x63, 0x62, 0x77, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0xca, 0x02, 0x1a, 0x43, 0x62, 0x77, 0x73, 0x5c, 0x4c, 0x6f, 0x67,
	0x67, 0x69, 0x6e, 0x67, 0x5c, 0x47, 0x72, 0x70, 0x63, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0xe2, 0x02, 0x23, 0x43, 0x62, 0x77, 0x73, 0x5c, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e,
	0x67, 0x5c, 0x47, 0x72, 0x70, 0x63, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cbws_logging_v1alpha1_log_severity_proto_rawDescOnce sync.Once
	file_cbws_logging_v1alpha1_log_severity_proto_rawDescData = file_cbws_logging_v1alpha1_log_severity_proto_rawDesc
)

func file_cbws_logging_v1alpha1_log_severity_proto_rawDescGZIP() []byte {
	file_cbws_logging_v1alpha1_log_severity_proto_rawDescOnce.Do(func() {
		file_cbws_logging_v1alpha1_log_severity_proto_rawDescData = protoimpl.X.CompressGZIP(file_cbws_logging_v1alpha1_log_severity_proto_rawDescData)
	})
	return file_cbws_logging_v1alpha1_log_severity_proto_rawDescData
}

var file_cbws_logging_v1alpha1_log_severity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cbws_logging_v1alpha1_log_severity_proto_goTypes = []interface{}{
	(LogSeverity)(0), // 0: cbws.logging.v1alpha1.LogSeverity
}
var file_cbws_logging_v1alpha1_log_severity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cbws_logging_v1alpha1_log_severity_proto_init() }
func file_cbws_logging_v1alpha1_log_severity_proto_init() {
	if File_cbws_logging_v1alpha1_log_severity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cbws_logging_v1alpha1_log_severity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cbws_logging_v1alpha1_log_severity_proto_goTypes,
		DependencyIndexes: file_cbws_logging_v1alpha1_log_severity_proto_depIdxs,
		EnumInfos:         file_cbws_logging_v1alpha1_log_severity_proto_enumTypes,
	}.Build()
	File_cbws_logging_v1alpha1_log_severity_proto = out.File
	file_cbws_logging_v1alpha1_log_severity_proto_rawDesc = nil
	file_cbws_logging_v1alpha1_log_severity_proto_goTypes = nil
	file_cbws_logging_v1alpha1_log_severity_proto_depIdxs = nil
}
