// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cbws/service_management/service_usage/v1alpha1/service_management.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cbws/go-cbws-grpc/cbws/iam/options/v1alpha1"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	longrunning "google.golang.org/genproto/googleapis/longrunning"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListServicesRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{0}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

func (m *ListServicesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type ListServicesResponse struct {
	// The list of matching services.
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{1}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

// Request message for EnableService method.
type EnableServiceRequest struct {
	// Relative resource of service in project in format: projects/test-project/services/iam.cbws.xyz
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableServiceRequest) Reset()         { *m = EnableServiceRequest{} }
func (m *EnableServiceRequest) String() string { return proto.CompactTextString(m) }
func (*EnableServiceRequest) ProtoMessage()    {}
func (*EnableServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{2}
}

func (m *EnableServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableServiceRequest.Unmarshal(m, b)
}
func (m *EnableServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableServiceRequest.Marshal(b, m, deterministic)
}
func (m *EnableServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableServiceRequest.Merge(m, src)
}
func (m *EnableServiceRequest) XXX_Size() int {
	return xxx_messageInfo_EnableServiceRequest.Size(m)
}
func (m *EnableServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableServiceRequest proto.InternalMessageInfo

func (m *EnableServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnableServiceMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableServiceMetadata) Reset()         { *m = EnableServiceMetadata{} }
func (m *EnableServiceMetadata) String() string { return proto.CompactTextString(m) }
func (*EnableServiceMetadata) ProtoMessage()    {}
func (*EnableServiceMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{3}
}

func (m *EnableServiceMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableServiceMetadata.Unmarshal(m, b)
}
func (m *EnableServiceMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableServiceMetadata.Marshal(b, m, deterministic)
}
func (m *EnableServiceMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableServiceMetadata.Merge(m, src)
}
func (m *EnableServiceMetadata) XXX_Size() int {
	return xxx_messageInfo_EnableServiceMetadata.Size(m)
}
func (m *EnableServiceMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableServiceMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_EnableServiceMetadata proto.InternalMessageInfo

// Operation payload for EnableService method.
type EnableServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableServiceResponse) Reset()         { *m = EnableServiceResponse{} }
func (m *EnableServiceResponse) String() string { return proto.CompactTextString(m) }
func (*EnableServiceResponse) ProtoMessage()    {}
func (*EnableServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{4}
}

func (m *EnableServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableServiceResponse.Unmarshal(m, b)
}
func (m *EnableServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableServiceResponse.Marshal(b, m, deterministic)
}
func (m *EnableServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableServiceResponse.Merge(m, src)
}
func (m *EnableServiceResponse) XXX_Size() int {
	return xxx_messageInfo_EnableServiceResponse.Size(m)
}
func (m *EnableServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableServiceResponse proto.InternalMessageInfo

// Request message for DisableService method.
type DisableServiceRequest struct {
	// Relative resource of service in project in format: projects/test-project/services/iam.cbws.xyz
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableServiceRequest) Reset()         { *m = DisableServiceRequest{} }
func (m *DisableServiceRequest) String() string { return proto.CompactTextString(m) }
func (*DisableServiceRequest) ProtoMessage()    {}
func (*DisableServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{5}
}

func (m *DisableServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableServiceRequest.Unmarshal(m, b)
}
func (m *DisableServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableServiceRequest.Marshal(b, m, deterministic)
}
func (m *DisableServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableServiceRequest.Merge(m, src)
}
func (m *DisableServiceRequest) XXX_Size() int {
	return xxx_messageInfo_DisableServiceRequest.Size(m)
}
func (m *DisableServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableServiceRequest proto.InternalMessageInfo

func (m *DisableServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DisableServiceMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableServiceMetadata) Reset()         { *m = DisableServiceMetadata{} }
func (m *DisableServiceMetadata) String() string { return proto.CompactTextString(m) }
func (*DisableServiceMetadata) ProtoMessage()    {}
func (*DisableServiceMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{6}
}

func (m *DisableServiceMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableServiceMetadata.Unmarshal(m, b)
}
func (m *DisableServiceMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableServiceMetadata.Marshal(b, m, deterministic)
}
func (m *DisableServiceMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableServiceMetadata.Merge(m, src)
}
func (m *DisableServiceMetadata) XXX_Size() int {
	return xxx_messageInfo_DisableServiceMetadata.Size(m)
}
func (m *DisableServiceMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableServiceMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DisableServiceMetadata proto.InternalMessageInfo

// Operation payload for DisableService method.
type DisableServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableServiceResponse) Reset()         { *m = DisableServiceResponse{} }
func (m *DisableServiceResponse) String() string { return proto.CompactTextString(m) }
func (*DisableServiceResponse) ProtoMessage()    {}
func (*DisableServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a5b2c20bf824b9e, []int{7}
}

func (m *DisableServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableServiceResponse.Unmarshal(m, b)
}
func (m *DisableServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableServiceResponse.Marshal(b, m, deterministic)
}
func (m *DisableServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableServiceResponse.Merge(m, src)
}
func (m *DisableServiceResponse) XXX_Size() int {
	return xxx_messageInfo_DisableServiceResponse.Size(m)
}
func (m *DisableServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableServiceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListServicesRequest)(nil), "cbws.service_management.service_usage.v1alpha1.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "cbws.service_management.service_usage.v1alpha1.ListServicesResponse")
	proto.RegisterType((*EnableServiceRequest)(nil), "cbws.service_management.service_usage.v1alpha1.EnableServiceRequest")
	proto.RegisterType((*EnableServiceMetadata)(nil), "cbws.service_management.service_usage.v1alpha1.EnableServiceMetadata")
	proto.RegisterType((*EnableServiceResponse)(nil), "cbws.service_management.service_usage.v1alpha1.EnableServiceResponse")
	proto.RegisterType((*DisableServiceRequest)(nil), "cbws.service_management.service_usage.v1alpha1.DisableServiceRequest")
	proto.RegisterType((*DisableServiceMetadata)(nil), "cbws.service_management.service_usage.v1alpha1.DisableServiceMetadata")
	proto.RegisterType((*DisableServiceResponse)(nil), "cbws.service_management.service_usage.v1alpha1.DisableServiceResponse")
}

func init() {
	proto.RegisterFile("cbws/service_management/service_usage/v1alpha1/service_management.proto", fileDescriptor_3a5b2c20bf824b9e)
}

var fileDescriptor_3a5b2c20bf824b9e = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0xcd, 0x4f, 0xd4, 0x4e,
	0x18, 0xc7, 0xd3, 0x42, 0xf8, 0xf1, 0x1b, 0x5f, 0x0e, 0x05, 0xdc, 0xa5, 0xab, 0x01, 0x6b, 0xa2,
	0x9b, 0x8d, 0xdb, 0x11, 0x38, 0xa8, 0x44, 0x13, 0xcb, 0x4b, 0xb8, 0x68, 0x24, 0x4b, 0xf4, 0x60,
	0x36, 0x21, 0xd3, 0xee, 0x58, 0x46, 0xdb, 0x99, 0xda, 0x99, 0x82, 0x2f, 0xe1, 0xc2, 0xc5, 0x97,
	0xab, 0xff, 0x89, 0xfc, 0x17, 0x7b, 0xd5, 0x78, 0xe0, 0x22, 0x1a, 0xff, 0x00, 0x13, 0x6f, 0x9c,
	0xcc, 0xb6, 0xd3, 0xd2, 0x86, 0x26, 0x58, 0x49, 0x8c, 0xa7, 0xdd, 0x3c, 0xdf, 0x67, 0xbe, 0xcf,
	0x33, 0x9f, 0xce, 0x33, 0x03, 0x56, 0x1c, 0x7b, 0x8b, 0x43, 0x8e, 0xc3, 0x4d, 0xe2, 0xe0, 0x75,
	0x1f, 0x51, 0xe4, 0x62, 0x1f, 0x53, 0x91, 0x85, 0x22, 0x8e, 0x5c, 0x0c, 0x37, 0x67, 0x90, 0x17,
	0x6c, 0xa0, 0x99, 0x92, 0x4c, 0x33, 0x08, 0x99, 0x60, 0x9a, 0x39, 0x30, 0x32, 0x4b, 0xe4, 0x82,
	0x91, 0x99, 0x1a, 0xe9, 0x57, 0xe2, 0xc2, 0x04, 0xf9, 0x90, 0x05, 0x82, 0x30, 0xca, 0x0f, 0x6b,
	0xc8, 0x40, 0x62, 0xac, 0xdf, 0xfa, 0xb3, 0x0e, 0xe5, 0xea, 0x4b, 0x2e, 0x63, 0xae, 0x87, 0xa1,
	0xc7, 0xa8, 0x1b, 0x46, 0x94, 0x12, 0xea, 0x42, 0x16, 0xe0, 0x10, 0xe5, 0x4b, 0x9c, 0x97, 0x49,
	0x28, 0x20, 0x10, 0x51, 0xca, 0x44, 0x41, 0xad, 0xe5, 0x54, 0xc7, 0x23, 0xd9, 0x96, 0xf5, 0xc9,
	0x9c, 0x10, 0x62, 0xce, 0xa2, 0x30, 0x2b, 0x3b, 0x95, 0x93, 0x1e, 0x13, 0xec, 0xf5, 0xd6, 0x6d,
	0xbc, 0x81, 0x36, 0x09, 0x0b, 0x93, 0x04, 0x63, 0x15, 0x8c, 0xdd, 0x25, 0x5c, 0xac, 0x25, 0xcd,
	0xf2, 0x0e, 0x7e, 0x16, 0x61, 0x2e, 0xb4, 0x9b, 0x60, 0x24, 0x40, 0x21, 0xa6, 0xa2, 0xae, 0x4c,
	0x2b, 0xcd, 0xff, 0x17, 0x2e, 0xee, 0x5b, 0xea, 0x81, 0xd5, 0x00, 0x93, 0x41, 0xc8, 0x9e, 0x60,
	0x47, 0xf0, 0x04, 0xf3, 0xf3, 0x17, 0x2f, 0xe1, 0x6a, 0x12, 0xe9, 0xc8, 0x05, 0xc6, 0x53, 0x30,
	0x5e, 0x74, 0xe4, 0x01, 0xa3, 0x1c, 0x6b, 0x6b, 0x60, 0x54, 0x22, 0xe1, 0x75, 0x65, 0x7a, 0xa8,
	0x79, 0x6a, 0xf6, 0x7a, 0xc5, 0x6f, 0x65, 0x4a, 0xcf, 0x4e, 0x66, 0x64, 0x40, 0x30, 0xbe, 0x4c,
	0x91, 0xed, 0xe1, 0x54, 0x92, 0xfd, 0xd7, 0xc0, 0x30, 0x45, 0x3e, 0x96, 0xdd, 0x0f, 0xed, 0x5b,
	0x6a, 0x27, 0x0e, 0x18, 0x35, 0x30, 0x51, 0x58, 0x70, 0x0f, 0x0b, 0xd4, 0x43, 0x02, 0x1d, 0x11,
	0xd2, 0xbe, 0x8d, 0x6b, 0x60, 0x62, 0x89, 0xf0, 0x2a, 0x35, 0xea, 0xe0, 0x5c, 0x71, 0x45, 0x56,
	0xe4, 0x88, 0x92, 0x56, 0x99, 0xfd, 0x39, 0x0a, 0xc6, 0x64, 0xec, 0xc1, 0x60, 0xd3, 0xf2, 0xbf,
	0xf6, 0x43, 0x05, 0xa7, 0xf3, 0x38, 0xb5, 0xc5, 0xaa, 0xd0, 0x4a, 0x3e, 0xaf, 0xbe, 0x74, 0x32,
	0x13, 0x49, 0xe6, 0x93, 0xd2, 0xb7, 0xde, 0x28, 0x60, 0xa9, 0xa2, 0x57, 0x29, 0x66, 0xed, 0x4e,
	0x45, 0x97, 0xfb, 0xe9, 0xf0, 0xa4, 0x70, 0xf7, 0xac, 0x98, 0xfe, 0xce, 0x6e, 0xe3, 0x3f, 0xe9,
	0xfd, 0x6e, 0xb7, 0x31, 0xec, 0x11, 0x2e, 0x76, 0x3e, 0x7e, 0x7f, 0xaf, 0x36, 0xb5, 0xcb, 0x87,
	0xb3, 0xf9, 0x2a, 0x39, 0xab, 0xb7, 0xd3, 0xd3, 0x0c, 0x5b, 0xdb, 0xe9, 0xbc, 0x72, 0xed, 0xb3,
	0x0a, 0xce, 0x14, 0x7a, 0xd4, 0x2a, 0xe3, 0x2a, 0x3b, 0x93, 0xfa, 0x05, 0x33, 0x19, 0x46, 0x33,
	0x77, 0x07, 0x1c, 0x6e, 0xc3, 0xf8, 0xf2, 0x8f, 0xd1, 0xac, 0xa7, 0xa9, 0x03, 0xaa, 0x57, 0x1d,
	0x46, 0x79, 0xe4, 0xe3, 0x70, 0x9d, 0xf4, 0x62, 0x9c, 0xb3, 0x46, 0x3b, 0x87, 0x73, 0x90, 0x92,
	0x83, 0x99, 0xb1, 0x84, 0xad, 0xed, 0x79, 0x1c, 0x37, 0x38, 0xaf, 0xb4, 0xb4, 0x3d, 0x15, 0x9c,
	0x2d, 0x1e, 0x7f, 0x6d, 0xb9, 0x2a, 0xd9, 0xd2, 0x51, 0x3c, 0x0e, 0xed, 0x57, 0xa5, 0x6f, 0xbd,
	0x55, 0xc0, 0xf2, 0x09, 0x6b, 0xfd, 0x2d, 0xb6, 0x73, 0x86, 0xf9, 0x9b, 0x6c, 0x7b, 0x49, 0x87,
	0xf3, 0x4a, 0x4b, 0x9f, 0xeb, 0x5b, 0x13, 0x52, 0x4a, 0xea, 0xa7, 0x17, 0xf4, 0xc1, 0x87, 0x46,
	0x0d, 0x94, 0x4b, 0x0b, 0xaf, 0x95, 0x47, 0x37, 0x5c, 0x22, 0x36, 0x22, 0xdb, 0x74, 0x98, 0x0f,
	0xe3, 0x17, 0xce, 0x65, 0xed, 0xc1, 0x6f, 0xdb, 0x0d, 0x03, 0x07, 0xe6, 0xdf, 0xbc, 0x76, 0xf1,
	0x81, 0xeb, 0xab, 0x53, 0x8b, 0xf6, 0x16, 0xef, 0xe6, 0x6f, 0xad, 0xee, 0x4a, 0x67, 0x75, 0xb1,
	0xfb, 0x50, 0x66, 0x7c, 0x53, 0x9b, 0xc7, 0x64, 0x74, 0x53, 0x24, 0xf6, 0x48, 0xfc, 0x1c, 0xcd,
	0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xb4, 0xb5, 0x2b, 0x08, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceUsageServiceClient is the client API for ServiceUsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceUsageServiceClient interface {
	// Enables a service for a project, so it can be used
	// for the project.
	//
	// Operation<response: EnableServiceResponse>
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Enables a service for a project, so it can be used
	// for the project.
	//
	// Operation<response: EnableServiceResponse>
	EnableService(ctx context.Context, in *EnableServiceRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Disables a service for a project, so it can no longer be
	// be used for the project. It prevents accidental usage that may cause
	// unexpected billing charges or security leaks.
	//
	// Operation<response: DisableServiceResponse>
	DisableService(ctx context.Context, in *DisableServiceRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
}

type serviceUsageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceUsageServiceClient(cc grpc.ClientConnInterface) ServiceUsageServiceClient {
	return &serviceUsageServiceClient{cc}
}

func (c *serviceUsageServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, "/cbws.service_management.service_usage.v1alpha1.ServiceUsageService/ListServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceUsageServiceClient) EnableService(ctx context.Context, in *EnableServiceRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/cbws.service_management.service_usage.v1alpha1.ServiceUsageService/EnableService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceUsageServiceClient) DisableService(ctx context.Context, in *DisableServiceRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/cbws.service_management.service_usage.v1alpha1.ServiceUsageService/DisableService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceUsageServiceServer is the server API for ServiceUsageService service.
type ServiceUsageServiceServer interface {
	// Enables a service for a project, so it can be used
	// for the project.
	//
	// Operation<response: EnableServiceResponse>
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Enables a service for a project, so it can be used
	// for the project.
	//
	// Operation<response: EnableServiceResponse>
	EnableService(context.Context, *EnableServiceRequest) (*longrunning.Operation, error)
	// Disables a service for a project, so it can no longer be
	// be used for the project. It prevents accidental usage that may cause
	// unexpected billing charges or security leaks.
	//
	// Operation<response: DisableServiceResponse>
	DisableService(context.Context, *DisableServiceRequest) (*longrunning.Operation, error)
}

// UnimplementedServiceUsageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceUsageServiceServer struct {
}

func (*UnimplementedServiceUsageServiceServer) ListServices(ctx context.Context, req *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (*UnimplementedServiceUsageServiceServer) EnableService(ctx context.Context, req *EnableServiceRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableService not implemented")
}
func (*UnimplementedServiceUsageServiceServer) DisableService(ctx context.Context, req *DisableServiceRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableService not implemented")
}

func RegisterServiceUsageServiceServer(s *grpc.Server, srv ServiceUsageServiceServer) {
	s.RegisterService(&_ServiceUsageService_serviceDesc, srv)
}

func _ServiceUsageService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceUsageServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cbws.service_management.service_usage.v1alpha1.ServiceUsageService/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceUsageServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceUsageService_EnableService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceUsageServiceServer).EnableService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cbws.service_management.service_usage.v1alpha1.ServiceUsageService/EnableService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceUsageServiceServer).EnableService(ctx, req.(*EnableServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceUsageService_DisableService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceUsageServiceServer).DisableService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cbws.service_management.service_usage.v1alpha1.ServiceUsageService/DisableService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceUsageServiceServer).DisableService(ctx, req.(*DisableServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceUsageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cbws.service_management.service_usage.v1alpha1.ServiceUsageService",
	HandlerType: (*ServiceUsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _ServiceUsageService_ListServices_Handler,
		},
		{
			MethodName: "EnableService",
			Handler:    _ServiceUsageService_EnableService_Handler,
		},
		{
			MethodName: "DisableService",
			Handler:    _ServiceUsageService_DisableService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cbws/service_management/service_usage/v1alpha1/service_management.proto",
}
